import { FaMoon, FaSun } from "react-icons/fa";
import { Icon } from "@chakra-ui/react";
export const light_theme = {
    dailyColor: "#0082FB",
    bgColor: "white",
    accentColor: "#0064e0",
    textColor: "black",
    subtleText: "gray",
    subtleBg: "gray.300",
    buttonColor: "black",
    priceBoxColor: "none",
    priceBoxSubtle: "gray.300",
    priceBoxAccent: "#0082FB",
    priceIcon: "black",
    descriptionBoxColor: "none",
    descriptionBoxSubtle: "none",
    navbarBg: "rgba(255, 255, 255, 0.3)",
    drawerIcons: "black",
    drawerHighlighted: "none",
    countryChoiceContent: "white",
    alertBg: "#d4d4d8",
    profileButtonBg: "none",
    profileBarBg: "rgba(255, 255, 255, 0.3)",
    teacherProfileBox: "none",
    themeIcon: <Icon as={FaSun} color="yellow.400" />
}

export const dark_theme = {
    dailyColor: "#0082FB",
    bgColor: "#000000",
    accentColor: "#0064e0",
    textColor: "white",
    subtleText: "gray",
    subtleBg: "gray.300",
    buttonColor: "#0064e0",
    priceBoxColor: "#212121ff",
    priceBoxSubtle: "#383838ff",
    priceBoxAccent: "#0064e0",
    priceIcon: "white",
    descriptionBoxColor: "#212121ff",
    descriptionBoxSubtle: "#383838ff",
    navbarBg: "rgba(0, 0, 0, 0.5)",
    drawerIcons: "white",
    drawerHighlighted: "#212121ff",
    countryChoiceContent: "black",
    alertBg: "#212121ff",
    profileButtonBg: "#212121ff",
    profileCardBox: "#212121ff",
    profileBarBg: "rgba(0, 0, 0, 0.5)",
    teacherProfileBox: "#212121ff",
    themeIcon: <Icon as={FaMoon} color="gray.400" />
}